### ISSUE TITLE
Deploy blog 

### ISSUE THREAD

**Issue by digitalsoba** [CSUN-SeniorDesign/matabit-blog#13]
Upload the blog into the EC2 instance but **Do not use git clone.** Instead zip or tarball the file and upload it the EC2. _Hint use rsycn_

**Comment by shahedsalehian** [comment]
matabit-blog folder was compressed with `tar -zcvf matabit-blog.tar.gz matabit-blog` and then transferred to the remote server with `scp matabit-blog.tar.gz ubuntu@matabit.org:/home/ubuntu`. Afterwards the tarball file was moved from the ubuntu home directory to /var/www as root and then unpacked with `tar -xvzf matabit-blog.tar.gz`
