### ISSUE TITLE
Create VPC on AWS

### ISSUE THREAD

**Issue by digitalsoba** [CSUN-SeniorDesign/matabit-blog#6]
● 3 public subnets in 3 different availability zones (AZ) with at least 1024 available IP addresses per subnet. 
● 3 private subnets in 3 different availability zones (AZ) with at least 4096 available IP addresses per subnet. ● 1 route table for the public subnets 
● 1 route table for the private subnets 
● 1 Internet Gateway (IG) attached to the default route of the public subnet routing table

**Comment by shahedsalehian** [comment]
Public/Private Subnets are established, with the public subnet carrying the main routing table which also has a internet gateway attached.
